server:
  disable: true

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push
    batchwait: 5s

scrape_configs:
  - job_name: hydra-log
    static_configs:
      - targets:
          - localhost
        labels:
          job: hydra-log
          service_name: hydra
          __path__: /opt/log/hydra.log
