services:

  grafana:
    image: grafana/grafana:11.2.0
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - GF_INSTALL_PLUGINS=grafana-pyroscope-app
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    volumes:
      - ./.docker/grafana/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./.docker/grafana/datasources:/etc/grafana/provisioning/datasources:ro

  prometheus:
    image: quay.io/prometheus/prometheus:v2.51.2
    restart: unless-stopped
    ports:
      - "9090:9090"
    command:
      - "--web.console.templates=/etc/prometheus/consoles"
      - "--web.console.libraries=/etc/prometheus/console_libraries"
      - "--storage.tsdb.retention.time=1h"
      - "--config.file=/etc/prometheus/prometheus.yaml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.enable-lifecycle"
      - "--web.route-prefix=/"
      - "--web.enable-admin-api"
      - "--web.enable-remote-write-receiver"
      - "--enable-feature=native-histograms"
      - "--enable-feature=exemplar-storage"
      - "--enable-feature=otlp-write-receiver"
    volumes:
      - ./.docker/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.49.1
    privileged: true
    restart: unless-stopped
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /dev/disk/:/dev/disk:ro

  loki:
    image: grafana/loki:3.1.0
    restart: unless-stopped
    command: [
      "-config.file=/etc/loki/config.yaml",
      "-target=all"
    ]
    volumes:
      - ./.docker/loki/config.yaml:/etc/loki/config.yaml:ro

  tempo:
    image: grafana/tempo:2.5.0
    init: true
    restart: unless-stopped
    command: [
      "-config.file=/etc/tempo/config.yaml"
    ]
    volumes:
      - ./.docker/tempo/config.yaml:/etc/tempo/config.yaml:ro

  pyroscope:
    image: grafana/pyroscope:1.7.1
    restart: unless-stopped
