auth_enabled: false

server:
  http_listen_port: 3100

common:
  storage:
    filesystem:
      chunks_directory: /tmp/loki/chunks
      rules_directory: /tmp/loki/rules
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory
  replication_factor: 1
  path_prefix: /tmp/loki

schema_config:
  configs:
    - store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index
        period: 24h

limits_config:
  reject_old_samples_max_age: 720h
  ingestion_rate_mb: 64
  ingestion_burst_size_mb: 128
  max_streams_per_user: 0
  max_global_streams_per_user: 500000
  per_stream_rate_limit: 1000MB

ingester:
  query_store_max_look_back_period: 720h
