global:
  evaluation_interval: 30s
  scrape_interval: 15s
scrape_configs:
  - job_name: hydra
    honor_labels: true
    metrics_path: /admin/metrics/prometheus
    static_configs:
      - targets:
          - 'hydra:4445'

  - job_name: collector
    honor_labels: true
    static_configs:
      - targets:
          - 'collector:8888'

  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
      - targets:
          - 'cadvisor:8080'
